timApp/timdb/models/folder.py
from typing import Optional

from documentmodel.document import Document
from tim_app import db
from timdb.blocktypes import blocktypes
from timdb.dbutils import insert_block, copy_default_rights
from timdb.models.docentry import DocEntry
from timdb.timdbexception import TimDbException
from utils import split_location, join_location

ROOT_FOLDER_ID = -1


class Folder(db.Model):
    __bind_key__ = 'tim_main'
    __tablename__ = 'folder'
    id = db.Column(db.Integer, db.ForeignKey('block.id'), primary_key=True)
    name = db.Column(db.Text, nullable=False)
    location = db.Column(db.Text, nullable=False)

    @staticmethod
    def get_root() -> 'Folder':
        return Folder(id=ROOT_FOLDER_ID, name='', location='')

    @staticmethod
    def get_by_id(fid) -> Optional['Folder']:
        return Folder.query.get(fid) if fid != ROOT_FOLDER_ID else Folder.get_root()

    @staticmethod
    def find_by_location(location, name) -> Optional['Folder']:
        return Folder.query.filter_by(name=name, location=location).first()

    @staticmethod
    def find_by_full_path(path) -> Optional['Folder']:
        parent_loc, name = split_location(path)
        return Folder.find_by_location(parent_loc, name)

    def is_root(self) -> bool:
        return self.id == -1

    def get_parent(self) -> Optional['Folder']:
        if self.is_root():
            return None
        parent_loc, name = split_location(self.location)
        return Folder.find_by_location(parent_loc, name) if name else Folder.get_root()

    def get_full_path(self) -> str:
        return join_location(self.location, self.name)

    def get_document(self, relative_path: str, create_if_not_exist=False, creator_group_id: int = None) -> Optional[
        DocEntry]:
        doc = DocEntry.query.filter_by(name=join_location(self.get_full_path(), relative_path)).first()
        if doc is not None:
            doc.document = Document(doc_id=doc.id)
            return doc
        if create_if_not_exist:
            assert creator_group_id is not None
            rel_folder, _ = split_location(relative_path)
            Folder.create(join_location(self.get_full_path(), rel_folder), owner_group_id=creator_group_id,
                          commit=False)
            return DocEntry.create(join_location(self.get_full_path(), relative_path), owner_group_id=creator_group_id)
        else:
            return None

    @staticmethod
    def create(path: str, owner_group_id: int, commit=True, apply_default_rights=False) -> 'Folder':
        """Creates a new folder with the specified name. If the folder already exists, it is returned.

        :param apply_default_rights: Whether to apply default rights from parents.
        :param commit: Whether to commit the changes.
        :param path: The name of the folder to be created.
        :param owner_group_id: The id of the owner group.
        :returns: The created or existing folder.
        """

        if '\0' in path:
            raise TimDbException('Folder name cannot contain null characters.')

        path = path.strip('/')

        # Root folder is special case
        if not path:
            return Folder.get_root()

        rel_path, rel_name = split_location(path)
        folder = Folder.query.filter_by(name=rel_name, location=rel_path).first()
        if folder is not None:
            return folder

        block_id = insert_block(path, owner_group_id, blocktypes.FOLDER, commit=False)

        f = Folder(id=block_id, name=rel_name, location=rel_path)
        db.session.add(f)

        # Make sure that the parent folder exists
        Folder.create(rel_path, owner_group_id, commit=False)

        if apply_default_rights:
            copy_default_rights(f.id, blocktypes.FOLDER, commit=False)

        if commit:
            db.session.commit()

        return f

timApp/routes/login.py
"""Routes for login view."""
from options import get_option
import codecs
import random
import string

import requests
import requests.exceptions
from flask import Blueprint, render_template
from yubico_client import Yubico
from yubico_client.yubico_exceptions import YubicoError

from routes.notify import send_email
from timdb.models.user import User
from .common import *
from .logger import log_error

login_page = Blueprint('login_page',
                       __name__,
                       url_prefix='')  # TODO: Better URL prefix.


def get_real_name(email):
    atindex = email.index('@')
    if atindex <= 0:
        return email
    parts = email[0:atindex].split('.')
    parts2 = [part.capitalize() if len(part) > 1 else part.capitalize() + '.' for part in parts]
    return ' '.join(parts2)


def is_valid_email(email):
    return re.match('^[\w\.-]+@([\w-]+\.)+[\w-]+$', email) is not None


@login_page.route("/logout", methods=['POST'])
def logout():
    user_id, = verify_json_params('user_id', require=False)
    if user_id is not None and user_id != getCurrentUserId():
        group = get_other_users()
        group.pop(str(user_id), None)
        session['other_users'] = group
    else:
        session.pop('user_id', None)
        session.pop('user_name', None)
        session.pop('email', None)
        session.pop('real_name', None)
        session.pop('appcookie', None)
        session.pop('altlogin', None)
        session.pop('came_from', None)
        session.pop('last_doc', None)
        session.pop('anchor', None)
        session.pop('other_users', None)
        session.pop('adding_user', None)
        session['user_name'] = 'Anonymous'
    return jsonResponse(dict(current_user=get_current_user(), other_users=get_other_users_as_list()))


@login_page.route("/login")
def login():
    save_came_from()
    if logged_in():
        flash('You are already logged in.')
        return safe_redirect(session.get('came_from', '/'))
    if request.args.get('korppiLogin'):
        return login_with_korppi()
    elif request.args.get('emailLogin'):
        return login_with_email()
    elif request.args.get('emailSignup'):
        return signup_with_email()
    else:
        return render_template('loginpage.html',
                               hide_require_text=True,
                               anchor=request.args.get('anchor'))


@login_page.route("/korppiLogin")
def login_with_korppi():
    add_user = get_option(request, 'add_user', False)
    if not logged_in() and add_user:
        return abort(403, 'You must be logged in before adding users to session.')
    if session.get('adding_user') is None:
        session['adding_user'] = add_user
    urlfile = request.url_root + "korppiLogin"
    save_came_from()

    if not session.get('appcookie'):
        random_hex = codecs.encode(os.urandom(24), 'hex').decode('utf-8')
        session['appcookie'] = random_hex
    url = "https://korppi.jyu.fi/kotka/interface/allowRemoteLogin.jsp"
    korppi_down_text = 'Korppi seems to be down, so login is currently not possible. Try again later.'
    try:
        r = requests.get(url, params={'request': session['appcookie']}, verify=True)
    except requests.exceptions.SSLError:
        return abort(503, korppi_down_text)
    
    if r.status_code != 200:
        return abort(503, korppi_down_text)
    korppi_response = r.text.strip()
    if not korppi_response:
        return redirect(url+"?authorize=" + session['appcookie'] + "&returnTo=" + urlfile, code=303)
    pieces = (korppi_response + "\n\n").split('\n')
    user_name = pieces[0]
    real_name = pieces[1]
    email = pieces[2]

    timdb = getTimDb()
    user_id = timdb.users.get_user_id_by_name(user_name)
    
    if user_id is None:
        # Try email
        user = timdb.users.get_user_by_email(email)
        if user is not None:
            # An email user signs in using Korppi for the first time. We update the user's username and personal
            # usergroup.
            user_id = user['id']
            group_id = timdb.users.get_personal_usergroup(user)
            timdb.users.update_user(user_id, user_name, real_name, email)
            timdb.users.add_user_to_korppi_group(user_id)
            timdb.users.set_usergroup_name(group_id, user_name)
        else:
            uid = timdb.users.create_user(user_name, real_name, email)
            gid = timdb.users.create_usergroup(user_name)
            timdb.users.add_user_to_group(gid, uid)
            timdb.users.add_user_to_korppi_group(uid)
            user_id = uid
    else:
        if real_name:
            timdb.users.update_user(user_id, user_name, real_name, email)

    user = {'id': user_id, 'name': user_name, 'real_name': real_name, 'email': email}

    set_user_to_session(user)

    return finish_login()


def set_user_to_session(user: Dict):
    adding = session.get('adding_user')
    session.pop('appcookie', None)
    session.pop('altlogin', None)
    session.pop('adding_user', None)
    if adding:
        if user['id'] in get_session_users_ids():
            flash('{} is already logged in.'.format(user['real_name']))
            return
        other_users = session.get('other_users', dict())
        other_users[str(user['id'])] = user
        session['other_users'] = other_users
    else:
        session['user_id'] = user['id']
        session['user_name'] = user['name']
        session['real_name'] = user['real_name']
        session['email'] = user['email']
        session.pop('other_users', None)


def login_with_email():
    if 'altlogin' in session and session['altlogin'] == 'login':
        session.pop('altlogin', None)
    else:
        session['altlogin'] = "login"

    return safe_redirect(session.get('came_from', '/'))


def signup_with_email():
    if 'altlogin' in session and session['altlogin'] == 'signup':
        session.pop('altlogin', None)
    else:
        session['altlogin'] = "signup"

    return safe_redirect(session.get('came_from', '/'))


@login_page.route("/altsignup", methods=['POST'])
def alt_signup():
    # Before password verification
    email = request.form['email']
    if not email or not is_valid_email(email):
        flash("You must supply a valid email address!")
        return finish_login(ready=False)
        
    password = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(6))
    
    timdb = getTimDb()
    timdb.users.create_potential_user(email, password)

    session.pop('altlogin', None)
    session.pop('user_id', None)
    session.pop('appcookie', None)
    session['user_name'] = 'Anonymous'
    session["email"] = email

    try:
        send_email(email, 'Your new TIM password', 'Your password is {}'.format(password))
        flash("A password has been sent to you. Please check your email.")
    except Exception as e:
        log_error('Could not send login email (user: {}, password: {}, exception: {})'.format(email, password, str(e)))
        flash('Could not send the email, please try again later. The error was: {}'.format(str(e)))

    return finish_login(ready=False)


@login_page.route("/altsignup2", methods=['POST'])
def alt_signup_after():
    # After password verification
    user_id = 0
    real_name = request.form['realname']
    email = session['email']
    username = email
    oldpass = request.form['token']
    password = request.form['password']
    confirm = request.form['passconfirm']
    save_came_from()
    timdb = getTimDb()

    if not timdb.users.test_potential_user(email, oldpass):
        return jsonResponse({'message': 'Authentication failure'}, 403)

    user_data = timdb.users.get_user_by_email(email)
    if user_data is not None:
        # User with this email already exists
        user_id = user_data['id']
        nameId = timdb.users.get_user_id_by_name(username)

        if nameId is not None and nameId != user_id:
            flash('User name already exists. Please try another one.', 'loginmsg')
            return finish_login(ready=False)

        # Use the existing user name; don't replace it with email
        username = user_data['name']
    else:
        if timdb.users.get_user_id_by_name(username) is not None:
            flash('User name already exists. Please try another one.', 'loginmsg')
            return finish_login(ready=False)
    
    if password != confirm:
        flash('Passwords do not match.', 'loginmsg')
        return finish_login(ready=False)
        
    if len(password) < 6:
        flash('A password should contain at least six characters.', 'loginmsg')
        return finish_login(ready=False)
    
    if user_id == 0:
        user_id = timdb.users.create_user(username, real_name, email, password=password)
        gid = timdb.users.create_usergroup(username)
        timdb.users.add_user_to_group(gid, user_id)
    else:
        timdb.users.update_user(user_id, username, real_name, email, password=password)
    
    timdb.users.delete_potential_user(email)
    
    session.pop('altlogin', None)
    session['user_id'] = user_id
    session['user_name'] = username
    session['real_name'] = real_name
    return finish_login()


@login_page.route("/altlogin", methods=['POST'])
def alt_login():
    save_came_from()
    email = request.form['email']
    password = request.form['password']
    session['adding_user'] = request.form.get('add_user', 'false').lower() == 'true'
    timdb = getTimDb()

    if timdb.users.test_user(email, password):
        # Registered user
        user = timdb.users.get_user_by_email(email)
        # Check if the users' group exists
        if (len(timdb.users.get_usergroups_by_name(user['name'])) == 0):
            gid = timdb.users.create_usergroup(user['name'])
            timdb.users.add_user_to_group(gid, user['id'])
        set_user_to_session(user)
        return finish_login()

    elif timdb.users.test_potential_user(email, password):
        # New user
        session['user_id'] = 0
        session['user_name'] = email

timApp/routes/settings.py
"""Routes for settings view."""
from flask import Blueprint, render_template
from jinja2 import TemplateNotFound

from theme import get_available_themes
from .common import *

settings_page = Blueprint('settings_page',
                          __name__,
                          url_prefix='/settings')


@settings_page.route('/')
def show():
    verifyLoggedIn()
    available_css_files = [{'name': theme.filename, 'desc': theme.description} for theme in get_available_themes()]

    try:
        return render_template('settings.html', css_files=available_css_files)
    except TemplateNotFound:
        abort(404)


@settings_page.route('/save', methods=['POST'])
def save_settings():
    verifyLoggedIn()
    update_preferences(request.get_json())
    show()  # Regenerate CSS
    return jsonResponse(get_preferences())

timApp/templates/common_head.html
<script src="{{ url_for('static', filename='scripts/draggable.js') }}"></script>
<script src="{{ url_for('static', filename='scripts/resizable.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('bower.static', filename='KaTeX/dist/katex.min.css') }}">
<script src="{{ url_for('static', filename='scripts/sidebarMenuCtrl.js') }}"></script>

<script>
    var sessionsettings = {{(session.settings or {})|tojson}};
    window.setsetting = function (setting, value) {
        $.ajax({
            type: 'POST',
            url: '/sessionsetting/' + setting + '/' + value,
            success: function (data) {
                console.log(data);
                sessionsettings[setting] = value;
            },
            error: function () {
                console.log("Could not set setting.");
            }
        });
    };

    window.GetURLParameter = function(sParam) {
        var sPageURL = window.location.search.substring(1);
        var sURLVariables = sPageURL.split('&');
        for (var i = 0; i < sURLVariables.length; i++) {
            var sParameterName = sURLVariables[i].split('=');
            if (sParameterName[0] == sParam) {
                return decodeURIComponent(sParameterName[1]);
            }
        }
    }
</script>

timApp/templates/doc_customcss.html
{{ (doc_css | safe ) if doc_css }}
<style type="text/css">
    {{ prefs.custom_css }}
</style>

timApp/templates/document.html
{% extends 'item.html' %}
{% block header %}
    {{ super() }}
    <script>
        {% if edit_mode %}
        var editMode = {{edit_mode|tojson|safe}};
        {% else %}
        var editMode = null;
        {% endif %}
    </script>
{% endblock %}

{% block itemlinks %}
    {{ super() }}
    {% if rights.teacher %}
         <li role="presentation" {{ active('view_page.teacher_view') }}><a id="headerTeacher" href="/teacher/{{ doc.fullname }}">Teacher view</a></li>
    {% endif %}
    {% if rights.see_answers %}
         <li role="presentation" {{ active('view_page.see_answers_view') }}><a id="headerAnswers" href="/answers/{{ doc.fullname }}">Answers</a></li>
    {% endif %}
     <li role="presentation" {{ active('view_page.lecture_view') }}><a id="headerLecture" href="/lecture/{{ doc.fullname }}">Lecture view</a></li>
     <li role="presentation" {{ active('view_page.velp_view') }}><a id="headerVelp" href="/velp/{{ doc.fullname }}">Velp view</a></li>
     <li role="presentation" {{ active('view_page.slide_document') }}><a id="headerSlide" href="/slide/{{ doc.fullname }}">Slide view</a></li>
    {% if translations %}
        <span style="float: right;">
                            {% for tr in translations %}
                                <li role="presentation"><a href="/{{ route }}/{{ tr.name }}">{{ tr.lang_id }}</a></li>
                                {% if not loop.last %}  {% endif %}
                            {% endfor %}
                        </span>
        <span style="clear: left"></span>
    {% endif %}
{% endblock %}

timApp/templates/item.html
{% extends 'base.html' %}
{%- macro active(endpoint) -%}
    {%- if request.endpoint == endpoint -%}
        class="active"
    {%- endif -%}
{%- endmacro -%}
{% block ngmodules %}
    {{ super() }}
    {{ ['ngFileUpload']|map('map_format', "'%s'")|join(', ')|safe }},
{% endblock %}
{% block ngscripts %}
    {{ super() }}
    <script src="{{ url_for('bower.static', filename='ng-file-upload/ng-file-upload-all.min.js') }}"></script>
{% endblock %}
{% block head %}
    {{ super() }}
    <script>
        var docId = {{doc.id|tojson}};
        var docName = {{doc.fullname|tojson}};
        var rights = {{rights|tojson}};
    </script>
    <script src="{{ url_for('static', filename='scripts/breadcrumbs.js') }}"></script>
{% endblock %}
{% block header %}
    {{ super() }}
    <div class="nav nav-tabs">    {% block itemlinks %}
        <li role="presentation" {{ active('view_page.view_document') }}><a id="headerView" href="/view/{{ doc.fullname }}">View</a></li>
        {% if rights.manage %}
             <li role="presentation" {{ active('manage_page.manage') }}><a id="headerManage" href="/manage/{{ doc.fullname }}">Manage</a></li>
        {% endif %}
    {% endblock %}</div>
    {% include 'breadcrumbs.html' %}
{% endblock %}

timApp/templates/lectureInfo.html
{% extends "document.html" %}
{% block title %}Lecture info{% endblock %}
{% block head %}
    {{ super() }}

    <script src="{{ url_for('static', filename='scripts/controllers/lectureInfoController.js') }}"></script>

    <script>
        var lectureId = {{lectureId|tojson}};
        var lectureCode = {{lectureCode|tojson}};
        var lectureStartTime = {{lectureStartTime|tojson}};
        var lectureEndTime = {{lectureEndTime|tojson}};
        var inLecture = {{in_lecture|tojson}};
    </script>

{% endblock %}
{% block content %}
    <div ng-controller="LectureInfoController">
        <pop-up-dialog show="showLectureForm" caption="'Edit lecture'">
            <ng-include
                    src="'{{ url_for('static', filename='templates/start_lecture.html') }}'"></ng-include>
        </pop-up-dialog>
        <div class="panel panel-default">
            <div class="panel-heading">Lecture info</div>
            <div class="panel-body">
                <strong>Lecture code:</strong>

                <p ng-bind="code"></p>

                <strong>Start time:</strong>

                <p ng-bind="lectureStartTime | timdate"></p>

                <strong>End time:</strong>

                <p ng-bind="lectureEndTime | timdate"></p>

                <div ng-show="isLecturer">
                    <!--TODO: Preview questions. Needs directive from the question preview and then just use it.-->
                    <strong>Questions asked:</strong>
                    <ul>
                        <li ng-repeat="question in questions">
                            <a ng-click="editPoints(question.asked_id)">{{ "{{ question.json.title }}" }}</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">Lecture wall</div>
            <div class="panel-body">
                <textarea class="form-control" data-ng-model="msg" readonly id="lectureInfoWall"></textarea>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">Find answers <span ng-show="!isLecturer" ng-bind="selectedUser.user_name"></span>
            </div>
            <div class="panel-body">
                <label ng-show="isLecturer">User name
                    <select class="form-control" ng-model="selectedUser"
                            ng-options="user.user_name for user in answerers track by user.user_id">
                    </select>
                </label>
                <button class="timButton" ng-click="drawCharts(selectedUser)">Show answers</button>
                <button class="timButton" ng-show="isLecturer" ng-click="drawCharts()">Show all</button>

                <div ng-repeat="question in questions" style="margin-bottom: 2em">
                    <p class="bold" ng-show="showPoints"
                       ng-bind-html="question.json.title">{{ "{{question.json.title}}" }}</p>
                    <p ng-show="showPoints"
                       ng-bind-html="question.json.questionText">{{ "{{question.json.questionText}}" }}</p>
                    <show-chart-directive canvas='answerChart{{ "{{question.asked_id }}" }}'
                                          control='dynamicAnswerShowControls[$index]'
                                          class="chart"></show-chart-directive>
                    <canvas id='answerChart{{ "{{question.asked_id }}" }}' width='400' height='300'></canvas>
                    <p ng-show="showPoints">Points: <span ng-bind="points[$index]"> </span></p>
                </div>

                <p id="infoBox"></p>
            </div>
        </div>

        <div ng-show="isLecturer" class="panel panel-default">
            <div class="panel-heading">
                Actions
            </div>
            <div class="panel-body">
                <button class="timButton" ng-click="editLecture(lectureName)">Edit lecture</button>
                <button class="btn btn-danger" ng-click="deleteLecture()">Delete lecture</button>
            </div>
        </div>
    </div>
{% endblock %}

timApp/templates/loginpage.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
    <script>
        $(document).ready(function () {
            var target_url = {{ url_for('login_page.login_with_korppi')|tojson }};
            var separator = target_url.indexOf('?') >= 0 ? '&' : '?';
            var came_from_raw = {{ (came_from or '')|tojson }};
            var came_from = encodeURIComponent(came_from_raw.replace("#", "%23"));
            var anchor_raw = {{ anchor|tojson if anchor else "window.location.hash.replace('#', '')"|safe }};
            var anchor = encodeURIComponent(anchor_raw);
            $("#anchor").val(anchor_raw);
            window.korppiLogin = function () {
                window.location.replace(target_url
                + separator
                + 'came_from='
                + came_from
                + '&anchor='
                + anchor);
            }
        });
    </script>

    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <form class="form-horizontal" method="POST" action="/altlogin">
                <p class="text-center">
                    {% if not hide_require_text %}
                        Login is required for this document.
                    {% endif %}
                    You can either login with Korppi
                </p>

                <button class="timButton center-block" type="button" onclick="korppiLogin()">Login with Korppi</button>
                <p class="text-center">
                    or with your email address if you have a TIM email account.
                </p>

                <input type="hidden" name="came_from" value="{{ came_from or '' }}">
                <input id="anchor" type="hidden" name="anchor" value="">

                <div class="form-group">
                    <label for="email" class="control-label col-sm-4">Email</label>
                    <div class="col-sm-6">
                        <input class="form-control" id="email" name="email" type="email" value="{{ session.email }}">
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="col-sm-4 control-label">Password</label>
                    <div class="col-sm-6">
                        <input class="form-control" id="password" name="password" type="password">
                    </div>
                </div>

                <button class="center-block timButton" type="submit">Login</button>
            </form>
        </div>
    </div>
{% endblock %}

timApp/templates/manage_folder.html
{% extends 'manage.html' %}
{% set obj_name = 'folder' %}
{% block managecontent %}
    <div class="panel panel-default">
        <div class="panel-heading">Name and location</div>
        <div class="panel-body">
            <form>
                <div class="form-group">
                    <label for="newName" class="control-label">Folder name:</label>
                    <div class="input-group">
                        <input class="form-control" id="newName" type="text" ng-model="newName">
                        <span class="input-group-btn">
                            <button ng-click="renameFolder(newName)" class="timButton" ng-disabled="newName === oldName">
                            Update
                        </button>
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="newFolderName" class="control-label">Location:</label>
                    <div class="input-group">
                        <input class="form-control" id="newFolderName" type="text"
                                                  ng-model="newFolderName">
                        <span class="input-group-btn">
                            <button ng-click="moveFolder(newFolderName)" class="timButton"
                                ng-disabled="newFolderName === oldFolderName">Update
                        </button>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="margin">
        <button class="timButton" ng-click="deleteFolder(doc.id)">Delete folder</button>
    </div>
{% endblock %}

timApp/templates/question_asked_student.html
<fieldset class="popUpWindow">
	<div>
		<link rel="stylesheet" href="{{ url_for('static', filename='windowstyle.css')}}">
		<link rel="stylesheet" href="{{ url_for('static', filename='progressbarstyle.css')}}">
		<h1>Question: </h1>
	</div>
	<div class="questionAskedWindow">
		<progress max="100" value="60">
			<strong>Time left: 60s</strong>
		</progress>
		<span class="progresslabel">40s</span>
		<div>
			<label>Question?</label>
			<label>Options for answering</label>
		</div>
		<div class="buttons">
			<button type="button">Send</button>
		</div>
	</div>
</fieldset>

timApp/templates/view_content.html
<div id="pars">
    {% include 'paragraphs.html' %}
    {% if rights.editable %}
        <div class="addBottomContainer hidden-print" ng-class="{'height-35': editing}">
            <button class="addBottom timButton">Add paragraph</button>
            <!--
            <button class="pasteRefBottom timButton">Paste as reference here</button>
            <button class="pasteBottom timButton">Paste as content here</button>
            -->
        </div>
    {% endif %}
</div>

timApp/templates/view_head.html
<script src="{{ url_for('static', filename='scripts/view_html.js') }}"></script>
<script src="{{ url_for('static', filename='scripts/pareditor.js') }}"></script>
<script src="{{ url_for('bower.static', filename='rangyinputs/rangyinputs-jquery.js') }}"></script>
<script src="{{ url_for('bower.static', filename='ace-builds/src-min-noconflict/ace.js') }}"></script>
<script src="{{ url_for('bower.static', filename='ace-builds/src-min-noconflict/ext-language_tools.js') }}"></script>
<script src="{{ url_for('bower.static', filename='angular-ui-ace/ui-ace.js') }}"></script>
<script src="{{ url_for('static', filename='scripts/answerbrowser3.js') }}"></script>
<script src="{{ url_for('static', filename='scripts/directives/popupMenu.js') }}"></script>
<script src="{{ url_for('static', filename='scripts/directives/refPopup.js') }}"></script>
<script src="{{ url_for('static', filename='scripts/directives/nameArea.js') }}"></script>